on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet
      run: dotnet restore src/App/App.sln 

    - name: Build app
      run: dotnet build src/App/App.csproj 

  testing-debug:  
    runs-on: windows-latest
    needs: build 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
    - name: Setup .NET
      uses: actions/setup-dotnet@v4 
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet
      run: dotnet restore src/App/App.sln

    - name: Test app
      run: dotnet test src/test/Test.csproj --configuration Debug 

